### ISSUE TITLE
Using the code exactly as written from the readme results in `ModuleNotFoundError: No module named 'flask_sqlalchemy'`

### ISSUE THREAD

**Issue by abankspdx** [pallets-eco/flask-sqlalchemy#1154]
I run:

```
pip install flask
pip install sqlalchemy
pip install -U flask-sqlalchemy
```

And then run the code from the README:

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = 'sqlite:///:memory:'
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True, nullable=False)

with app.app_context():
    db.create_all()

    db.session.add(User(username="example"))
    db.session.commit()

    users = db.session.execute(db.select(User)).scalars()
```

(Only modified the database URI)

This results in: `ModuleNotFoundError: No module named 'flask_sqlalchemy'`. 

Environment:

- Python version: 3.10
- Flask-SQLAlchemy version: 3.0.2
- SQLAlchemy version: 1.4.46

**Comment by abankspdx** [comment]
I'll include:

```
(venv) [src] pip install -U flask-sqlalchemy                                                                                                                                                  main  ✗ ✭ ✈ ✱
Requirement already satisfied: flask-sqlalchemy in ./venv/lib/python3.8/site-packages (3.0.2)
Requirement already satisfied: SQLAlchemy>=1.4.18 in ./venv/lib/python3.8/site-packages (from flask-sqlalchemy) (1.4.46)
Requirement already satisfied: Flask>=2.2 in ./venv/lib/python3.8/site-packages (from flask-sqlalchemy) (2.2.2)
Requirement already satisfied: itsdangerous>=2.0 in ./venv/lib/python3.8/site-packages (from Flask>=2.2->flask-sqlalchemy) (2.1.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./venv/lib/python3.8/site-packages (from Flask>=2.2->flask-sqlalchemy) (6.0.0)
Requirement already satisfied: Jinja2>=3.0 in ./venv/lib/python3.8/site-packages (from Flask>=2.2->flask-sqlalchemy) (3.1.2)
Requirement already satisfied: Werkzeug>=2.2.2 in ./venv/lib/python3.8/site-packages (from Flask>=2.2->flask-sqlalchemy) (2.2.2)
Requirement already satisfied: click>=8.0 in ./venv/lib/python3.8/site-packages (from Flask>=2.2->flask-sqlalchemy) (8.1.3)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.8/site-packages (from importlib-metadata>=3.6.0->Flask>=2.2->flask-sqlalchemy) (3.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.8/site-packages (from Jinja2>=3.0->Flask>=2.2->flask-sqlalchemy) (2.1.2)
```

And

```
(venv) [src] flask run                                                                                                                                                                        main  ✗ ✭ ✈ ✱
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
  File "/Users/alex/Code/lavender-systems/lavender/api/src/app.py", line 49, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
```

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided.

Please use [our Discord](https://discord.gg/pallets) for discussion about your own code. This tracker is for issues related to the project itself.

**Comment by abankspdx** [comment]
Sorry, isn't the quick start project code?

**Comment by davidism** [comment]
No, it's code you write and run locally. As I said, it all works fine for me. Please take further help question off the issue tracker.

**Comment by dchevell** [comment]
@abankspdx this is a local python installation/environment issue.

Here, we see you've installed `flask-sqlalchemy` in your virtual environment, i.e. in the "venv" folder in your project;
```
(venv) [src] pip install -U flask-sqlalchemy                                                                                                                                                  
Requirement already satisfied: flask-sqlalchemy in ./venv/lib/python3.8/site-packages (3.0.2)
```
But when you run `flask run`, we can see that `flask` is running from your homebrew python installation - i.e. _outside_ of the virtual environment, where you _haven't_ installed flask-sqlalchemy:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
```

So the issue has nothing to do with this library.

My suggestion is that you uninstall Flask from your system-level python:
```
deactivate
pip3 uninstall flask
```
then reactivate your virtual environment, and try again. That way, when you call `flask run` you can be sure it's running the one from your virtual environment, not from your system's globally installed packages.
