### ISSUE TITLE
3.0 tries to create table from model definition that maps to a view in postgresql

### ISSUE THREAD

**Issue by awiprayitno** [pallets-eco/flask-sqlalchemy#1230]
I have the following model in models.py that maps to a built in view in postgresql: pg_timezone_names:
`
class TimezoneNames(db.Model):
	__tablename__ = "pg_timezone_names"

	name = db.Column(db.Text, primary_key=True)
	abbrev  = db.Column(db.Text)
	utc_offset = db.Column(db.Interval)
	is_dst = db.Column(db.Boolean)
`

When I call db.create_all() in 2.0 everything is ok, but after I upgrade to 3.0, it tried to create pg_timezone_names  and throws the following error:
`
Traceback (most recent call last):
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateTable: relation "pg_timezone_names" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ibos/api_reservasi/reservasi.py", line 178, in <module>
    db.create_all()
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 884, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 865, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5581, in create_all
    bind._run_ddl_visitor(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3226, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2430, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 924, in visit_metadata
    self.traverse_single(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 963, in visit_table
    )._invoke_with(self.connection)
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1526, in _execute_ddl
    ret = self._execute_context(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ibos/prod_reservasi/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "pg_timezone_names" already exists

[SQL:
CREATE TABLE pg_timezone_names (
        name TEXT NOT NULL,
        abbrev TEXT,
        utc_offset INTERVAL,
        is_dst BOOLEAN,
        PRIMARY KEY (name)
)

]
`
This is the view definition in postgresql:
`
reservasi=> \d+ pg_timezone_names
                       View "pg_catalog.pg_timezone_names"
   Column   |   Type   | Collation | Nullable | Default | Storage  | Description
------------+----------+-----------+----------+---------+----------+-------------
 name       | text     |           |          |         | extended |
 abbrev     | text     |           |          |         | extended |
 utc_offset | interval |           |          |         | plain    |
 is_dst     | boolean  |           |          |         | plain    |
View definition:
 SELECT pg_timezone_names.name,
    pg_timezone_names.abbrev,
    pg_timezone_names.utc_offset,
    pg_timezone_names.is_dst
   FROM pg_timezone_names() pg_timezone_names(name, abbrev, utc_offset, is_dst);
`
Environment:

- Python version: 3.10.6
- Flask-SQLAlchemy version: 3.0.3
- SQLAlchemy version: 2.0.9

**Comment by davidism** [comment]
Flask-SQLAlchemy doesn't do anything different than SQLAlchemy. Perhaps you updated SQLAlchemy as well and something changed?
